import type { Rule } from "@/store/rules";

export type PresetCategory = "privacy" | "network" | "regional" | "catchall";

export interface RulePreset {
  id: string;
  category: PresetCategory;
  nameKey: string;
  descKey: string;
  rules: Omit<Rule, "id">[];
}

export const PRESET_CATEGORY_ORDER: PresetCategory[] = [
  "privacy",
  "network",
  "regional",
  "catchall",
];

export const PRESET_CATEGORY_KEYS: Record<PresetCategory, string> = {
  privacy: "rules.categoryPrivacy",
  network: "rules.categoryNetwork",
  regional: "rules.categoryRegional",
  catchall: "rules.categoryCatchAll",
};

export const RULE_PRESETS: RulePreset[] = [
  // ── Privacy & Blocking ──────────────────────────────────────────────
  {
    id: "block-ads",
    category: "privacy",
    nameKey: "rules.presetBlockAds",
    descKey: "rules.presetBlockAdsDesc",
    rules: [
      { type: "DOMAIN-SUFFIX", match: "doubleclick.net", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "googlesyndication.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "googleadservices.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "adnxs.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "ads.yahoo.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "ads.facebook.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "ad.doubleclick.net", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "moatads.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "adcolony.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "unity3d.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "appsflyer.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "mopub.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "serving-sys.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "rubiconproject.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "pubmatic.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "openx.net", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "adform.net", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "criteo.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "taboola.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "outbrain.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "adsrvr.org", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "casalemedia.com", action: "REJECT" },
      { type: "DOMAIN-KEYWORD", match: "adservice", action: "REJECT" },
      { type: "DOMAIN-KEYWORD", match: "pagead", action: "REJECT" },
      { type: "DOMAIN-KEYWORD", match: "adsystem", action: "REJECT" },
    ],
  },
  {
    id: "block-trackers",
    category: "privacy",
    nameKey: "rules.presetBlockTrackers",
    descKey: "rules.presetBlockTrackersDesc",
    rules: [
      { type: "DOMAIN-SUFFIX", match: "analytics.google.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "google-analytics.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "googletagmanager.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "hotjar.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "mixpanel.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "segment.io", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "segment.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "amplitude.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "fullstory.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "mouseflow.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "crazyegg.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "newrelic.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "sentry.io", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "bugsnag.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "app-measurement.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "adjust.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "branch.io", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "facebook.net", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "scorecardresearch.com", action: "REJECT" },
      { type: "DOMAIN-KEYWORD", match: "tracker", action: "REJECT" },
      { type: "DOMAIN-KEYWORD", match: "telemetry", action: "REJECT" },
    ],
  },
  {
    id: "block-malware",
    category: "privacy",
    nameKey: "rules.presetBlockMalware",
    descKey: "rules.presetBlockMalwareDesc",
    rules: [
      { type: "DOMAIN-SUFFIX", match: "malwaredomainlist.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "malwareurl.com", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "phishing.army", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "ransomwaretracker.abuse.ch", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "cybercrime-tracker.net", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "zeustracker.abuse.ch", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "feodotracker.abuse.ch", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "sslbl.abuse.ch", action: "REJECT" },
      { type: "DOMAIN-SUFFIX", match: "urlhaus.abuse.ch", action: "REJECT" },
      { type: "DOMAIN-KEYWORD", match: "malware", action: "REJECT" },
      { type: "DOMAIN-KEYWORD", match: "phishing", action: "REJECT" },
      { type: "DOMAIN-KEYWORD", match: "cryptominer", action: "REJECT" },
    ],
  },

  // ── Network ─────────────────────────────────────────────────────────
  {
    id: "bypass-lan",
    category: "network",
    nameKey: "rules.presetBypassLAN",
    descKey: "rules.presetBypassLANDesc",
    rules: [
      { type: "IP-CIDR", match: "127.0.0.0/8", action: "DIRECT" },
      { type: "IP-CIDR", match: "10.0.0.0/8", action: "DIRECT" },
      { type: "IP-CIDR", match: "172.16.0.0/12", action: "DIRECT" },
      { type: "IP-CIDR", match: "192.168.0.0/16", action: "DIRECT" },
      { type: "IP-CIDR", match: "::1/128", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "local", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "localhost", action: "DIRECT" },
    ],
  },
  {
    id: "bypass-apple",
    category: "network",
    nameKey: "rules.presetBypassApple",
    descKey: "rules.presetBypassAppleDesc",
    rules: [
      { type: "DOMAIN-SUFFIX", match: "apple.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "icloud.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "icloud-content.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "mzstatic.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "aaplimg.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "cdn-apple.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "apple-cloudkit.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "apple-mapkit.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "itunes.apple.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "apps.apple.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "push.apple.com", action: "DIRECT" },
      { type: "DOMAIN", match: "mesu.apple.com", action: "DIRECT" },
      { type: "DOMAIN", match: "swdist.apple.com", action: "DIRECT" },
      { type: "IP-CIDR", match: "17.0.0.0/8", action: "DIRECT" },
    ],
  },

  // ── Regional ────────────────────────────────────────────────────────
  {
    id: "china-direct",
    category: "regional",
    nameKey: "rules.presetChinaDirect",
    descKey: "rules.presetChinaDirectDesc",
    rules: [
      { type: "GEOIP", match: "CN", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "cn", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "baidu.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "qq.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "taobao.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "jd.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "163.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "bilibili.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "weibo.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "alipay.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "tmall.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "zhihu.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "douyin.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "toutiao.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "xiaomi.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "huawei.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "douban.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "meituan.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "pinduoduo.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "csdn.net", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "iqiyi.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "youku.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "sohu.com", action: "DIRECT" },
      { type: "IP-CIDR", match: "223.5.5.5/32", action: "DIRECT" },
      { type: "IP-CIDR", match: "119.29.29.29/32", action: "DIRECT" },
    ],
  },
  {
    id: "streaming-direct",
    category: "regional",
    nameKey: "rules.presetStreamingDirect",
    descKey: "rules.presetStreamingDirectDesc",
    rules: [
      { type: "DOMAIN-SUFFIX", match: "netflix.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "nflxvideo.net", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "nflxext.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "youtube.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "googlevideo.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "ytimg.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "spotify.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "scdn.co", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "spotifycdn.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "disneyplus.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "bamgrid.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "hulu.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "hbonow.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "hbomax.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "twitch.tv", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "ttvnw.net", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "primevideo.com", action: "DIRECT" },
      { type: "DOMAIN-SUFFIX", match: "aiv-cdn.net", action: "DIRECT" },
      { type: "DOMAIN-KEYWORD", match: "netflix", action: "DIRECT" },
      { type: "DOMAIN-KEYWORD", match: "spotify", action: "DIRECT" },
    ],
  },

  // ── Catch-all ───────────────────────────────────────────────────────
  {
    id: "global-proxy",
    category: "catchall",
    nameKey: "rules.presetGlobalProxy",
    descKey: "rules.presetGlobalProxyDesc",
    rules: [
      { type: "FINAL", match: "", action: "PROXY" },
    ],
  },
];
